name: store
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


# ------------------------ packages --------------------------- #

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider:
  bloc:
  flutter_bloc:
  equatable:
  # Network
  http:
  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_sign_in: ^6.2.1
  # Loading
  flutter_spinkit:
  modal_progress_hud_nsn:
  shimmer:
  # Icons
  iconsax:
  cupertino_icons: ^1.0.6
  # local storage
  get_storage:
  # utils:
  intl:
  logger:
  url_launcher:
  connectivity:
  flutter_native_splash: 
  smooth_page_indicator: 
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.0
  connectivity_plus: ^6.0.1
  delightful_toast: ^1.1.0
  restart_app: ^1.2.1
  flutter_facebook_auth: ^6.2.0
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  animated_text_kit:
  appinio_swiper: ^2.1.1
  flutter_localizations:
    sdk: flutter
# ------------------------ End-packages --------------------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

# ------------------------ Local Assets --------------------------- #


  assets:
    - assets/images/logos/
    - assets/images/on_board/
    - assets/images/auth/
    - assets/images/categories/
    - assets/images/banner/
    - assets/images/products/
    - assets/images/features/
    - assets/images/payment_method/
    - assets/images/network/
    - assets/images/chat/


# ------------------------ Local Fonts --------------------------- #

  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Bold.ttf
          - asset: assets/fonts/Poppins-ExtraBold.ttf
          - asset: assets/fonts/Poppins-SemiBold.ttf
          - asset: assets/fonts/Poppins-Medium.ttf
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 700    
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
